import { IconType } from "react-icons/lib";
import {
  MdDashboard,
  MdAssessment,
  MdBusinessCenter,
  MdPeople,
  MdMoney,
  MdAssignment,
  MdSettingsCell,
  MdDescription,
  MdDateRange,
  MdAnnouncement,
  MdPersonAdd,
  MdSearch,
  MdFeedback,
  MdLocalLibrary,
  MdPayment,
  MdNotifications,
  MdCalendarToday,
  MdCloudUpload,
  MdApi,
  MdLock,
  MdSettingsApplications,
  MdSchool,
  MdAssignmentTurnedIn,
} from "react-icons/md";
import { FaChevronCircleRight, FaChartBar } from "react-icons/fa";

// Type Definition
export type MenuItemProps = {
  menuItemText: string;
  menuItemLink?: string;
  Icon?: IconType;
  color?: string;
  submenu: boolean;
  subMenuItems: MenuItemProps[];
};

// Color Constants
const COLORS = {
  blue: "text-blue-500",
  green: "text-green-500",
  yellow: "text-yellow-500",
  red: "text-red-500",
  purple: "text-purple-500",
  pink: "text-pink-500",
  indigo: "text-indigo-500",
  teal: "text-teal-500",
  orange: "text-orange-500",
  cyan: "text-cyan-600",
  gray: "text-gray-500",
  lime: "text-lime-500",
};

// Base URL Constants
const BASE_URLS = {
  public: "/dashboard",
  admin: "/admindashboard",
  employee: "/employeedashboard",
  superAdmin: "/superadmindashboard",
};

// Public User Menu
export const publicUserMenuItems: MenuItemProps[] = [
  {
    menuItemText: "Dashboard",
    menuItemLink: `${BASE_URLS.public}/home`,
    Icon: MdDashboard,
    color: COLORS.blue,
    submenu: false,
    subMenuItems: [],
  },
  {
    menuItemText: "Certificate Applications",
    Icon: MdDescription,
    color: COLORS.green,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Apply for Heir Certificate",
        menuItemLink: `${BASE_URLS.public}/warish/apply`,
        Icon: FaChevronCircleRight,
        color: COLORS.yellow,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "View Application Status",
        menuItemLink: `${BASE_URLS.public}/warish/status`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Profile Management",
    Icon: MdPersonAdd,
    color: COLORS.purple,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "View Profile",
        menuItemLink: `${BASE_URLS.public}/profile/view`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Edit Profile",
        menuItemLink: `${BASE_URLS.public}/profile/edit`,
        Icon: FaChevronCircleRight,
        color: COLORS.pink,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Change Password",
        menuItemLink: `${BASE_URLS.public}/profile/change-password`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Payments",
    Icon: MdPayment,
    color: COLORS.lime,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Payment History",
        menuItemLink: `${BASE_URLS.public}/payments/history`,
        Icon: FaChevronCircleRight,
        color: COLORS.lime,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Payment Methods",
        menuItemLink: `${BASE_URLS.public}/payments/methods`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Announcements",
    menuItemLink: `${BASE_URLS.public}/announcements`,
    Icon: MdAnnouncement,
    color: COLORS.red,
    submenu: false,
    subMenuItems: [],
  },
  {
    menuItemText: "Feedback & Complaints",
    Icon: MdFeedback,
    color: COLORS.orange,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Submit Feedback",
        menuItemLink: `${BASE_URLS.public}/feedback`,
        Icon: FaChevronCircleRight,
        color: COLORS.orange,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "File Complaint",
        menuItemLink: `${BASE_URLS.public}/record-complaint`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Resources Center",
    Icon: MdLocalLibrary,
    color: COLORS.teal,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Official Documents",
        menuItemLink: `${BASE_URLS.public}/resources/documents`,
        Icon: FaChevronCircleRight,
        color: COLORS.teal,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "FAQs",
        menuItemLink: `${BASE_URLS.public}/resources/faqs`,
        Icon: FaChevronCircleRight,
        color: COLORS.cyan,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "User Guides",
        menuItemLink: `${BASE_URLS.public}/resources/user-guide`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Notifications",
    menuItemLink: `${BASE_URLS.public}/notifications`,
    Icon: MdNotifications,
    color: COLORS.pink,
    submenu: false,
    subMenuItems: [],
  },
  {
    menuItemText: "Calendar",
    menuItemLink: `${BASE_URLS.public}/calendar`,
    Icon: MdCalendarToday,
    color: COLORS.red,
    submenu: false,
    subMenuItems: [],
  },
  {
    menuItemText: "Support Center",
    menuItemLink: `${BASE_URLS.public}/help`,
    Icon: MdSearch,
    color: COLORS.teal,
    submenu: false,
    subMenuItems: [],
  },
];

// Admin Menu
export const adminMenuItems: MenuItemProps[] = [
  {
    menuItemText: "Admin Dashboard",
    menuItemLink: `${BASE_URLS.admin}/home`,
    Icon: MdDashboard,
    color: COLORS.blue,
    submenu: false,
    subMenuItems: [],
  },
  {
    menuItemText: "Communication",
    Icon: MdDashboard,
    color: COLORS.blue,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Compose Email",
        menuItemLink: `${BASE_URLS.admin}/manage-email/sent-email`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Email History",
        menuItemLink: `${BASE_URLS.admin}/manage-email/view-sent-email`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Operations Management",
    Icon: MdDashboard,
    color: COLORS.red,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Action Plans",
        menuItemLink: `${BASE_URLS.admin}/work-manage/view`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Work Status Tracking",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/work-status-change`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Fund Status",
        menuItemLink: `${BASE_URLS.admin}/fundstatus`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Work Details",
        menuItemLink: `${BASE_URLS.admin}/work-manage/scheme-wise`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Vendor Management",
    Icon: MdPeople,
    color: COLORS.red,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Register New Vendor",
        menuItemLink: `${BASE_URLS.admin}/manage-vendor/add`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Update Vendor Details",
        menuItemLink: `${BASE_URLS.admin}/manage-vendor/edit`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Vendor Directory",
        menuItemLink: `${BASE_URLS.admin}/manage-vendor/view`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Vendor Analytics",
        Icon: FaChartBar,
        color: COLORS.teal,
        submenu: true,
        subMenuItems: [
          {
            menuItemText: "Bid Participation Summary",
            menuItemLink: `${BASE_URLS.admin}/reports/vendor-participation`,
            Icon: FaChevronCircleRight,
            color: COLORS.blue,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Earnest Money Status",
            menuItemLink: `${BASE_URLS.admin}/reports/earnest-money`,
            Icon: FaChevronCircleRight,
            color: COLORS.green,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Technical Compliance",
            menuItemLink: `${BASE_URLS.admin}/reports/technical-compliance`,
            Icon: FaChevronCircleRight,
            color: COLORS.purple,
            submenu: false,
            subMenuItems: [],
          },
        ],
      },
    ],
  },
  {
    menuItemText: "Certificate Administration",
    Icon: MdDashboard,
    color: COLORS.red,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Certificate Applications",
        menuItemLink: `${BASE_URLS.admin}/manage-warish/view`,
        Icon: FaChevronCircleRight,
        color: COLORS.yellow,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Assignment Management",
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: true,
        subMenuItems: [
          {
            menuItemText: "Assign to Staff",
            menuItemLink: `${BASE_URLS.admin}/manage-warish/assign-staff`,
            Icon: FaChevronCircleRight,
            color: COLORS.blue,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Public Applications",
            menuItemLink: `${BASE_URLS.admin}/manage-warish/assign-citizen`,
            Icon: FaChevronCircleRight,
            color: COLORS.blue,
            submenu: false,
            subMenuItems: [],
          },
        ],
      },
      {
        menuItemText: "Approval Process",
        menuItemLink: `${BASE_URLS.admin}/manage-warish/approve`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Certificate Generation",
        menuItemLink: `${BASE_URLS.admin}/manage-warish/print`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Renewal Process",
        menuItemLink: `${BASE_URLS.admin}/manage-warish/renew`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Application Status",
        menuItemLink: `${BASE_URLS.admin}/manage-warish/status`,
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Application Management",
        Icon: MdBusinessCenter,
        color: COLORS.purple,
        submenu: true,
        subMenuItems: [
          {
            menuItemText: "Submit Application",
            menuItemLink: `${BASE_URLS.admin}/manage-warish/application`,
            Icon: FaChevronCircleRight,
            color: COLORS.teal,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Document Upload",
            menuItemLink: `${BASE_URLS.admin}/manage-warish/upload`,
            Icon: FaChevronCircleRight,
            color: COLORS.teal,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "View Applications",
            menuItemLink: `${BASE_URLS.admin}/manage-warish/view-application`,
            Icon: FaChevronCircleRight,
            color: COLORS.teal,
            submenu: false,
            subMenuItems: [],
          },
        ],
      },
    ],
  },
  {
    menuItemText: "Procurement Management",
    Icon: MdBusinessCenter,
    color: COLORS.purple,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Create Tender",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/add`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Active Tenders",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/open`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Technical Specifications",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/addtechnicaldetails`,
        Icon: FaChevronCircleRight,
        color: COLORS.teal,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Tender Modifications",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/edit`,
        Icon: FaChevronCircleRight,
        color: COLORS.orange,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Tender Registry",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/view`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Bid Management",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/addbidderdetails`,
        Icon: FaChevronCircleRight,
        color: COLORS.yellow,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Financial Details",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/addfinanicaldetails`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Contract Awards",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/workorderdetails`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Tender Cancellations",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/cancel-tender`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Document Management",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/upload`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Contract Administration",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/awardofcontract`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Order Cancellations",
        menuItemLink: `${BASE_URLS.admin}/manage-tender/cancel-work-order`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Document Generation",
    Icon: FaChevronCircleRight,
    color: COLORS.indigo,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Scrutiny Sheets",
        menuItemLink: `${BASE_URLS.admin}/generate/printscrutisheet`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Agreements",
        menuItemLink: `${BASE_URLS.admin}/generate/agrement`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Work Orders",
        menuItemLink: `${BASE_URLS.admin}/generate/work-order`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Supply Orders",
        menuItemLink: `${BASE_URLS.admin}/generate/supply-order`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Payment Certificates",
        menuItemLink: `${BASE_URLS.admin}/generate/payment-certificate`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Completion Certificates",
        menuItemLink: `${BASE_URLS.admin}/generate/completation-certificate`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "FY Completion Reports",
        menuItemLink: `${BASE_URLS.admin}/generate/completation-certificate2`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Document Covers",
        menuItemLink: `${BASE_URLS.admin}/generate/cover-page`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Financial Administration",
    Icon: MdAssessment,
    color: COLORS.indigo,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Payment Records",
        menuItemLink: `${BASE_URLS.admin}/addpaymentdetails`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Regulatory Compliance",
        Icon: MdMoney,
        color: COLORS.red,
        submenu: true,
        subMenuItems: [
          {
            menuItemText: "Security Deposits",
            menuItemLink: `${BASE_URLS.admin}/register/security`,
            Icon: FaChevronCircleRight,
            color: COLORS.yellow,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Labor Cess",
            menuItemLink: `${BASE_URLS.admin}/register/lebour-cess`,
            Icon: FaChevronCircleRight,
            color: COLORS.red,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "GST Compliance",
            menuItemLink: `${BASE_URLS.admin}/register/gst-register`,
            Icon: FaChevronCircleRight,
            color: COLORS.red,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Income Tax",
            menuItemLink: `${BASE_URLS.admin}/register/income-tax`,
            Icon: FaChevronCircleRight,
            color: COLORS.red,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Earnest Money",
            menuItemLink: `${BASE_URLS.admin}/register/earnest-money`,
            Icon: FaChevronCircleRight,
            color: COLORS.red,
            submenu: false,
            subMenuItems: [],
          },
        ],
      },
    ],
  },
  {
    menuItemText: "Reports & Analytics",
    Icon: MdAssessment,
    color: COLORS.blue,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Financial Reports",
        Icon: FaChartBar,
        color: COLORS.green,
        submenu: true,
        subMenuItems: [
          {
            menuItemText: "Budget Analysis",
            menuItemLink: `${BASE_URLS.admin}/reports/budget`,
            Icon: FaChevronCircleRight,
            color: COLORS.blue,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Expenditure Summary",
            menuItemLink: `${BASE_URLS.admin}/reports/expenditure`,
            Icon: FaChevronCircleRight,
            color: COLORS.green,
            submenu: false,
            subMenuItems: [],
          },
        ],
      },
      {
        menuItemText: "Performance Metrics",
        menuItemLink: `${BASE_URLS.admin}/reports/performance`,
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Application Statistics",
        menuItemLink: `${BASE_URLS.admin}/reports/applications`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Notice",
    Icon: MdSettingsCell,
    color: COLORS.indigo,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Add",
        menuItemLink: `${BASE_URLS.admin}/notice/add`,
        color: COLORS.cyan,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "View",
        menuItemLink: `${BASE_URLS.admin}/notice/view`,
        color: COLORS.cyan,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "System Configuration",
    Icon: MdSettingsCell,
    color: COLORS.red,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "System Utilities",
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: true,
        subMenuItems: [
          {
            menuItemText: "Email Services",
            menuItemLink: `${BASE_URLS.admin}/master/utils/emails-service`,
            Icon: FaChevronCircleRight,
            color: COLORS.purple,
            submenu: false,
            subMenuItems: [],
          },
          {
            menuItemText: "Notification Services",
            menuItemLink: `${BASE_URLS.admin}/master/utils/notifications`,
            Icon: FaChevronCircleRight,
            color: COLORS.purple,
            submenu: false,
            subMenuItems: [],
          },
        ],
      },
      {
        menuItemText: "Personnel Directory",
        menuItemLink: `${BASE_URLS.admin}/viewmenberdetails`,
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "System Messaging",
        menuItemLink: `${BASE_URLS.admin}/master/addimpsmessage`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Work Item Catalog",
        menuItemLink: `${BASE_URLS.admin}/master/addworkitems`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Form Repository",
        menuItemLink: `${BASE_URLS.admin}/master/uploadform`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "System Monitoring",
    Icon: MdSettingsApplications,
    color: COLORS.gray,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Audit Logs",
        menuItemLink: `${BASE_URLS.admin}/monitoring/audit-logs`,
        Icon: FaChevronCircleRight,
        color: COLORS.gray,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "System Health",
        menuItemLink: `${BASE_URLS.admin}/monitoring/health`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Integrations",
    Icon: MdApi,
    color: COLORS.indigo,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Payment Gateways",
        menuItemLink: `${BASE_URLS.admin}/integrations/payments`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "API Management",
        menuItemLink: `${BASE_URLS.admin}/integrations/api`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "User Administration",
    Icon: MdPeople,
    color: COLORS.blue,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Create User Account",
        menuItemLink: `${BASE_URLS.admin}/user/add`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Modify User Account",
        menuItemLink: `${BASE_URLS.admin}/user/edit`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "User Directory",
        menuItemLink: `${BASE_URLS.admin}/user`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Staff Directory",
        menuItemLink: `${BASE_URLS.admin}/staff`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Account Status",
        menuItemLink: `${BASE_URLS.admin}/userstatus-change`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  // water tanker management
  {
    menuItemText: "Water Tanker Management",
    Icon: MdDashboard,
    color: COLORS.blue,
    submenu: true,

    subMenuItems: [
      {
        menuItemText: "Service Fee Management",
        menuItemLink: `${BASE_URLS.admin}/water-tanker/fees`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Tanker Schedule",
        menuItemLink: `${BASE_URLS.admin}/water-tanker/schedule`,
        Icon: FaChevronCircleRight,
        color: COLORS.yellow,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Tanker Requests",
        menuItemLink: `${BASE_URLS.admin}/water-tanker/requests`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Tanker Maintenance",
        menuItemLink: `${BASE_URLS.admin}/water-tanker/availability`,  
        Icon: FaChevronCircleRight, 
        color: COLORS.purple,
        submenu: false, 
        subMenuItems: [],
      }
    ],
  }
];

// Employee Menu
export const employeeMenuItems: MenuItemProps[] = [
  {
    menuItemText: "Employee Dashboard",
    menuItemLink: `${BASE_URLS.employee}/home`,
    Icon: MdDashboard,
    color: COLORS.blue,
    submenu: false,
    subMenuItems: [],
  },
  {
    menuItemText: "Certificate Processing",
    Icon: MdAssignment,
    color: COLORS.red,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Assigned Applications",
        menuItemLink: `${BASE_URLS.employee}/warish/view-assigned`,
        Icon: FaChevronCircleRight,
        color: COLORS.yellow,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "New Application",
        menuItemLink: `${BASE_URLS.employee}/warish/apply`,
        Icon: FaChevronCircleRight,
        color: COLORS.yellow,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Process Applications",
        menuItemLink: `${BASE_URLS.employee}/warish/process`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Generate Certificates",
        menuItemLink: `${BASE_URLS.employee}/warish/generate`,
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Work Reporting",
    Icon: MdDateRange,
    color: COLORS.pink,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Daily Reports",
        menuItemLink: `${BASE_URLS.employee}/reports`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Performance Metrics",
        menuItemLink: `${BASE_URLS.employee}/reports/metrics`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Leave Management",
    Icon: MdDateRange,
    color: COLORS.pink,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Leave Application",
        menuItemLink: `${BASE_URLS.employee}/leave/apply`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Leave Balance",
        menuItemLink: `${BASE_URLS.employee}/leave/balance`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Leave History",
        menuItemLink: `${BASE_URLS.employee}/leave/history`,
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Document Management",
    Icon: MdDescription,
    color: COLORS.teal,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Upload Documents",
        menuItemLink: `${BASE_URLS.employee}/documents/upload`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "My Documents",
        menuItemLink: `${BASE_URLS.employee}/documents/view`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Shared Documents",
        menuItemLink: `${BASE_URLS.employee}/documents/shared`,
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Tasks",
    Icon: MdAssignmentTurnedIn,
    color: COLORS.cyan,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "My Tasks",
        menuItemLink: `${BASE_URLS.employee}/tasks`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Team Tasks",
        menuItemLink: `${BASE_URLS.employee}/tasks/team`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Training",
    Icon: MdSchool,
    color: COLORS.purple,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Courses",
        menuItemLink: `${BASE_URLS.employee}/training/courses`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Certifications",
        menuItemLink: `${BASE_URLS.employee}/training/certifications`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  //water tanker management
  {
    menuItemText: "Water Tanker Management",
    Icon: MdDashboard,
    color: COLORS.blue,
    submenu: true,

    subMenuItems: [
      
      {
        menuItemText: "Booking Requests",
        menuItemLink: `${BASE_URLS.employee}/water-tanker/booking`,
        Icon: FaChevronCircleRight,
        color: COLORS.yellow,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Service History",
        menuItemLink: `${BASE_URLS.employee}/water-tanker/history`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
    ],
  } 
];

// Super Admin Menu
export const superAdminMenuItems: MenuItemProps[] = [
  {
    menuItemText: "System Administration",
    Icon: MdPeople,
    color: COLORS.blue,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "User Accounts",
        menuItemLink: `${BASE_URLS.superAdmin}/user`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Staff Management",
        menuItemLink: `${BASE_URLS.superAdmin}/staff`,
        Icon: FaChevronCircleRight,
        color: COLORS.red,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Access Controls",
        menuItemLink: `${BASE_URLS.superAdmin}/access-controls`,
        Icon: FaChevronCircleRight,
        color: COLORS.indigo,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Audit Logs",
        menuItemLink: `${BASE_URLS.superAdmin}/audit-logs`,
        Icon: FaChevronCircleRight,
        color: COLORS.purple,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Infrastructure",
    Icon: MdCloudUpload,
    color: COLORS.gray,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Backup & Restore",
        menuItemLink: `${BASE_URLS.superAdmin}/infrastructure/backup`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Environment Settings",
        menuItemLink: `${BASE_URLS.superAdmin}/infrastructure/environment`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },
  {
    menuItemText: "Security Center",
    Icon: MdLock,
    color: COLORS.red,
    submenu: true,
    subMenuItems: [
      {
        menuItemText: "Security Policies",
        menuItemLink: `${BASE_URLS.superAdmin}/security/policies`,
        Icon: FaChevronCircleRight,
        color: COLORS.blue,
        submenu: false,
        subMenuItems: [],
      },
      {
        menuItemText: "Two-Factor Auth",
        menuItemLink: `${BASE_URLS.superAdmin}/security/2fa`,
        Icon: FaChevronCircleRight,
        color: COLORS.green,
        submenu: false,
        subMenuItems: [],
      },
    ],
  },

  
];
